
services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=airport_db
      - POSTGRES_USER=airport_user
      - POSTGRES_PASSWORD=airport_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "sleep 3 && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=airport_db
      - DB_USER=airport_user
      - DB_PASSWORD=airport_password
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=super_secret_key_12345
    depends_on:
      - db

volumes:
  postgres_data: