# Generated by Django 6.0.5 on 2026-05-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_rename_country_city_country_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('iata_code', models.CharField(max_length=2, unique=True)),
                ('created_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('model', models.CharField(max_length=125)),
                ('year', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('seats_per_row', models.IntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='locations.city')),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='base_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.airport'),
        ),
    ]
