# Generated by Django 6.0.5 on 2026-06-05 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('iata_code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='IATA код авіакомпанії повинен складатися рівно з 2 великих латинських літер або цифр (наприклад, UA, W6).', regex='^[A-Z0-9]{2}$')])),
                ('founded_year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('model', models.CharField(max_length=125)),
                ('year', models.DateTimeField()),
                ('rows', models.PositiveIntegerField()),
                ('seats_per_row', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='fleet.airline')),
            ],
            options={
                'verbose_name_plural': 'Airplanes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('iata_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='IATA код аеропорту повинен складатися рівно з 3 великих латинських літер (наприклад, KBP, LWO).', regex='^[A-Z]{3}$')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='locations.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='airline',
            name='airport',
            field=models.ManyToManyField(blank=True, related_name='airlines', to='fleet.airport'),
        ),
        migrations.CreateModel(
            name='AirplaneSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('seat', models.CharField(max_length=2)),
                ('class_type', models.CharField(choices=[('BUSINESS', 'business'), ('ECONOMY', 'economy')], default='ECONOMY', max_length=10)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='fleet.airplane')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('airplane', 'row', 'seat'), name='unique_airplane_seat')],
            },
        ),
    ]
