# Generated by Django 6.0.5 on 2026-06-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['name'], 'verbose_name_plural': 'Airplanes'},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='airline',
            name='base_airport',
        ),
        migrations.AddField(
            model_name='airline',
            name='airport',
            field=models.ManyToManyField(blank=True, related_name='airlines', to='fleet.airport'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='fleet.airline'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='rows',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='seats_per_row',
            field=models.PositiveIntegerField(),
        ),
    ]
