# Generated by Django 6.0.5 on 2026-06-08 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata_code',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='IATA The airline code must consist of exactly 2 capital Latin letters or numbers (for example, UA, W6).', regex='^[A-Z0-9]{2}$')]),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='IATA the airport code must consist of exactly 3 capital Latin letters (for example, KBP, LWO).', regex='^[A-Z]{3}$')]),
        ),
    ]
