# Generated by Django 6.0.5 on 2026-06-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_airplane_options_alter_airport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('seat', models.CharField()),
                ('class_type', models.CharField(choices=[('BUSINESS', 'business'), ('ECONOMY', 'economy')], default='ECONOMY', max_length=10)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='fleet.airplane')),
            ],
        ),
    ]
