# Generated by Django 6.0.5 on 2026-06-23 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_airline_founded_year_alter_airplane_year'),
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='flight_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.airplaneseat'),
        ),
    ]
