# Generated by Django 6.0.5 on 2026-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'booked'), ('USED', 'used'), ('PAID', 'paid'), ('CANCELLED', 'cancelled')], default='BOOKED', max_length=10),
        ),
    ]
