# Generated by Django 6.0.5 on 2026-06-05 13:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='The country code must consist of exactly 3 capital Latin letters.', regex='^[A-Z]{3}$')])),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'code'), name='unique_country_name_and_code')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.country')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_city_in_country')],
            },
        ),
    ]
