# Generated by Django 6.0.5 on 2026-06-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_country_city_country_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
